# version: 0.0
# os: linux
# hooks:
#     # BeforeBlockTraffic:
    #     - location: scripts/before_block_traffic.sh
    #       runas: root
    # AfterBlockTraffic:
    #     - location: scripts/after_block_traffic.sh
    #       runas: root
    # ApplicationStop:
    #     - location: scripts/application_stop.sh
    #       runas: root
    # BeforeInstall:
    #     - location: scripts/before_install.sh
    #       runas: root
    # AfterInstall:
    #     - location: scripts/after_install.sh
    #       runas: root
    # ApplicationStart:
    #     - location: scripts/application_start.sh
    #       runas: root
    # ValidateService:
    #     - location: scripts/validate_service.sh
    #       runas: root
    # BeforeAllowTraffic:
    #     - location: scripts/before_allow_traffic.sh
    #       runas: root
    # AfterAllowTraffic:
    #     - location: scripts/after_allow_traffic.sh
    #       runas: root

version: 0.0
os: linux
files:
  - source: /src
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root